### PR TITLE
Home Page

### PR DESCRIPTION
**Pull request by horsemaker**
⚠️ The site is not responsive. Try it at your own risk!

P.S.: If some parts work responsively, believe me, GOD exists!

recording

### CODE REVIEW

**Comment by AtulHande03a** [comment]
Eyes feel blessed .. the UI looks clean.. great work 🎉🎉

**Review by AtulHande03a — APPROVED** [review]

**Review by Varu98 — APPROVED** [review]
super clean ui 😄

**Review by MarkVed17 — APPROVED** [review]
Looks soothing to the eyes! Good choice of colors & typography. The green color does all the wonders!

**Review by tanveertkd — APPROVED** [review]
I'm not sure if you noticed, but there seems to be some empty space after the footer, apart from that this looks really good Yash! Great job! 👍

**Review by t007rushi — APPROVED** [review]
you can fix total height as footer must be fixed @ bottom but there is space left

**Review by MiheerTamkhane — APPROVED** [review]
What a soothing UX
Good work man.

**Pull request merged**
